name: PEP8 Check Out

on:
  push:
    paths:
      - '*.py'

jobs:
  flake8_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Flake8
        run: pip install flake8

      - name: Run Flake8
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: 'flake8_check'   # NOTE: this needs to be the same as the job name
        env:
          GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}
